import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/sections/Footer";
import Navbar from "@/components/sections/Navbar";

const avant = localFont({ src: "fonts/ITCAvantGardePro-Md.ttf" });

export const metadata: Metadata = {
  title: "Finbridge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${avant.className}`}>
        <Navbar />
        <main className="">
          <div className="">{children}</div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
